### ISSUE TITLE
Scrolling when dragMode set

### ISSUE THREAD

**Issue by SimonBarrettACT** [dcasia/nova-pill-filter#5] opened 2020-07-31 09:53 UTC
I'm experiencing a problem scrolling with the mouse over the filter pop-up when a filter is set to dragMode.

If the mouse is over any other filter or one a nova-pill-filter where dragMode is not enabled, scrolling works.

I am working on an iMac with latest version of Chrome.

![](https://user-images.githubusercontent.com/57679318/89023701-e3581600-d31b-11ea-8541-8b5f2dc6325d.gif)

**Comment by milewski** [comment] 2023-09-29 15:51
The problem was probably fixed on the latest version, I wasn't able to reproduce it

**Closed as completed by milewski** 2023-09-29 15:51 UTC
Labels: bug
